### ISSUE TITLE
Critical issue performance: if ecoindex is down, slows down site using badge

### ISSUE THREAD

**Issue by vvatelot** [cnumr/ecoindex_badge#130]
If ecoindex.fr and bff.ecoindex.fr is down, the badge slows down websites that try to display it

**Comment by yaaax** [comment]
Could you please be more precise when you say "slows down"?
I could reproduce a delay in displaying the badge itself (with a "?" icon inside), but all the content around was displayed normally.
If the issue is just the display of the badge itself, we can add a first default style (with the "?" icon) with a JS code executed on script load (and not after bff backend response)
